- name: remove firewalld service
  service: name=firewalld state=stopped enabled=no

- name: yum install Environmental package
  yum: name={{item}} state=present
  with_items:
    - wget
    - git
    - net-tools
    - bind-utils
    - iptables-services
    - bridge-utils 
    - bash-completion
    - lrzsz
    - vim

